### PR TITLE
Remove pwa from withPWA return value

### LINKED ISSUE #367: Invalid next.config.js with next-pwa
# Summary

Since the latest version of Next.js, `next.config.js` doesn't support any more invalid properties.
After running `npm run dev`, here's what we got:
```txt
warn  - Invalid next.config.js options detected: 
[
  {
    "instancePath": "",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "pwa"
    },
    "message": "must NOT have additional properties"
  }
] 
See more info here: https://nextjs.org/docs/messages/invalid-next-config
```

Related Next.js issue: https://github.com/vercel/next.js/issues/38909

# Versions

- `next-pwa`: 5.5.4
- `next`: 12.2.3

# How To Reproduce

Steps to reproduce the behavior: Basically install `next-pwa` in a Next.js project (latest Next.js version) and configure it in `next.config.js` with the `pwa` property.

# Expected Behaviors

Maybe, we should start using `next-pwa` differently?
No more `pwa` property inside `next.config.js`?

### PR DESCRIPTION
**Pull request by DavidSint**
In Next 12.2.3 a change was added saying that the `next.config.js` "must NOT have additional properties" and that the `pwa` property was considered as an additional property. Therefore, this commit deletes the `pwa` property from the calculated next config in the default exported function in index.js (aka the `withPWA` function). The returned next config therefore does not have the `pwa` field and the warning does not appear.

Resolves #367

### CODE REVIEW

**Review by olavoparno — CHANGES_REQUESTED** [review]
Can you lint according to what was before and only adjust the removal of the PWA key? This gives everyone much more confort in reviewing this PR

**Comment by DavidSint** [comment]
I'm not sure exactly what you mean @olavoparno? Are you saying that the PR violates something from a linting rule?

**Comment by olavoparno** [comment]
@DavidSint it is just that it seems you changed the indentation, didn't you?

**Comment by olavoparno** [comment]
Oh, you had to create a new object, right? Sorry, I did not notice it.

**Review by olavoparno — APPROVED** [review]

**Comment by DavidSint** [comment]
Thanks @olavoparno, so now it appears we have to wait for this workflow to be approved to run first

**Comment by shadowwalker** [comment]
Thanks for the pull request. I'm a bit behind obviously.

**Comment by felixmosh** [comment]
This PR breaks the config, since the `webpack` function takes the `pwa` from `options.config` which (doesn't exists anymore).

**Comment by ArianHamdi** [comment]
Same here. I just started with the 5.5.5 version.

**Comment by jamesformica** [comment]
Also having an issue. The `sw.js` (and other files) are no longer being outputted in the `public` NextJs folder, and are instead being outputted in the `.next` folder. We are on the latest version of next. This was previously working and nothing in our config has changed other than bumping the patch version. Have downgraded to `5.5.4` but would prefer a proper fix.

**Comment by trongithust** [comment]
This change make pwa from options.config always is {}. So, the plugin doesn't apply any config.

**Pull request merged**
